### ISSUE TITLE
There was a problem starting carla

### ISSUE THREAD

**Issue by hrz2000** [autonomousvision/plant#1]
![image](https://user-images.githubusercontent.com/79900945/200098291-983dcbe3-aff4-440d-a8f6-d0f49f12dd65.png)
When Carla is started, it ends directly instead of keeping active (I didn't end it manually). The gpu does not display the corresponding activity. What is the possible reason? There is no error prompt. It is difficult for me to find the problem

**Comment by kashyap7x** [comment]
Are you able to launch the server with the display enabled? You can see the [CARLA simulator docs](https://carla.readthedocs.io/en/latest/tuto_first_steps/#launching-carla-and-connecting-the-client) for details on this. If you are on a remote machine and do not have a display, you can also try launching the server with a docker image. Instructions for setting up docker are available [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker). Pull the docker image of CARLA 0.9.10.1 ```docker pull carlasim/carla:0.9.10.1```.

Docker 18:
```
docker run -it --rm -p 2000-2002:2000-2002 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 carlasim/carla:0.9.10.1 ./CarlaUE4.sh --world-port=2000 -opengl
```

Docker 19:
```Shell
docker run -it --rm --net=host --gpus '"device=0"' carlasim/carla:0.9.10.1 ./CarlaUE4.sh --world-port=2000 -opengl
```

Besides this, I don't think I have any other advice, since I haven't encountered this issue. You might find more useful information in the [CARLA forum](https://github.com/carla-simulator/carla/discussions/), [Discord channel](https://discord.gg/8kqACuC), or [GitHub issues](https://github.com/carla-simulator/carla/issues).

**Comment by hrz2000** [comment]
Thank you for your quick reply and suggestions. I tried again on Docker, and the program ended directly similarly. I guess it may be because of my remote machine, I can run normally on another machine. I raised this question on the carla forum. https://github.com/carla-simulator/carla/discussions/5916
