### ISSUE TITLE
The history trajectory usage

### ISSUE THREAD

**Issue by SiyuanHuang95** [autonomousvision/plant#8]
Hi, 

after reading the paper, I am wondering about the usage of using historical trajectory information, both ego and target cars. Have you compared the performance with/without that information?

Also, for the model with the perception module, the trajectory (if used) would become noisy since *perfect perception assumption* could not be held?

Best,

**Comment by RenzKa** [comment]
Hi,
this is indeed an interesting direction and could make it easier to reason about the future of the other vehicles. We input the speed of the vehicles which is also some kind of temporal information. We also show that this is very important information for the model. Inputting the trajectory directly could lead to similar results but we haven't tried it for the paper.

Yes, this of course heavily depends on the quality of the perception module. But this is already true for the single timestep input model.

Best

**Comment by SiyuanHuang95** [comment]
Hi,

For temporal information usage: Clear; thanks for your update.

For the perception module, I am wandering, what happened to the unstable perception results, like missing or ghost, would the trajectory be zig-zag since the detection results are different in adject frames?

**Comment by RenzKa** [comment]
Hi,
yes if the perception results are unstable and some crucial objects are missing in some frames the predicted trajectory would change since the prediction happens per frame. The PID controller which gets this predicted trajectory as input would smoothen the changes a bit. This means if the detections are only in a few frames incorrect the vehicle would not drive zig-zag.
